### ISSUE TITLE
error when changing commands

### ISSUE THREAD

**Issue by Eldarlz** [Roccoxx/Equipment-Sprites#1]
Hello. I have this problem: when the commands are swapped, the following error appears
![20240306230703_1](https://github.com/Roccoxx/Equipment-Sprites/assets/153284215/78293890-c8f7-48be-b320-d8914e82953d)
![20240306230704_1](https://github.com/Roccoxx/Equipment-Sprites/assets/153284215/3ad2b818-dc97-4588-9d25-ded628b7bf21)
![20240306230959_1](https://github.com/Roccoxx/Equipment-Sprites/assets/153284215/9926349a-6e3f-47fb-8792-7235e4f61892)
![20240306231446_1](https://github.com/Roccoxx/Equipment-Sprites/assets/153284215/757c59b9-f3f3-42f9-a2b3-544cfb8d6101)
![20240306231603_1](https://github.com/Roccoxx/Equipment-Sprites/assets/153284215/966233dd-6379-4651-b2b1-a276d9db73ed)

**Comment by Roccoxx** [comment]
Hello, which commands do you change?

**Comment by Eldarlz** [comment]
I mean, when you play 15 rounds, on the pug the players change places after several restarts, the problem appears

**Comment by Roccoxx** [comment]
Okay do you have error messages from this plugin in your .log files?

**Comment by Eldarlz** [comment]
> Хорошо, есть ли у вас сообщения об ошибках этого плагина в ваших файлах .log?

no, everything is clean there

**Comment by Roccoxx** [comment]
> > Хорошо, есть ли у вас сообщения об ошибках этого плагина в ваших файлах .log?
> 
> no, everything is clean there

Nice, so... are you using a public pug version? If it's the case, can you give me the link?

**Comment by Eldarlz** [comment]
> > > Хорошо, есть ли у вас сообщения об ошибках этого плагина в ваших файлах .log?
> > 
> > 
> > нет, там все чисто
> 
> Хорошо, так... вы используете общедоступную версию мопса? Если это так, можете ли вы дать мне ссылку?

pug from https://github.com/SmileYzn/PugMod

**Comment by Roccoxx** [comment]
> > > > Хорошо, есть ли у вас сообщения об ошибках этого плагина в ваших файлах .log?
> > > 
> > > 
> > > нет, там все чисто
> > 
> > 
> > Хорошо, так... вы используете общедоступную версию мопса? Если это так, можете ли вы дать мне ссылку?
> 
> pug from https://github.com/SmileYzn/PugMod

Thanks, I updated the plugin. Try and let me know if everything is OK please.

**Comment by Eldarlz** [comment]
> > > > > Хорошо, есть ли у вас сообщения об ошибках этого плагина в ваших файлах .log?
> > > > 
> > > > 
> > > > нет, там все чисто
> > > 
> > > 
> > > Хорошо, так... вы используете общедоступную версию мопса? Если это так, можете ли вы дать мне ссылку?
> > 
> > 
> > мопс с https://github.com/SmileYzn/PugMod
> 
> Спасибо, обновил плагин. Попробуйте и дайте мне знать, если все в порядке, пожалуйста.

Thank you. I played a few cards and everything works well.
